PATHS:
  DATASET: "./src/data/2410_iPAGE_SoilData_cleaned.csv"
  REPORT: "./src/visualizations/SWEETVIZ_REPORT.html"
  MODEL_DIR: "./app/src/models/checkpoints"
  SAVED_MODEL: "9_79.08538.pth"

STAPP:
  PAGES:
    DATA_OVERVIEW: "Data Overview"
    CORR: "Correlation Matrix"
    FEATURE_ANALYSIS: "Feature Analysis"
    RANDOM_FOREST: "RANDOM_FOREST"
    ABOUT: "About"
  STYLES:
    # BACKGROUND: "#f0f0f0"
    # TEXT: "#333333"
    BACKGROUND: "gray"
    TEXT: "white"
    WIDTH: "1000"
    HEIGHT: "600"

MODEL:
  BATCH_SIZE: 32
  IMG_FEATURE_EXTRACTOR:
    MODEL_TYPE: "resnet50" # "resnet18", "resnet34", "resnet50"
    PRETRAINED: true
    DROPOUT_RATE: 0.3 # Set to 0 if dropout is not needed
    FEATURE_DIM: 2048 # Feature dimension (depends on ResNet type, if using resnet18, resnet34, set to 512)
  PC_FEATURE_EXTRACTOR:
    DROPOUT_RATE: 0.3 # Set to 0 if dropout is not needed
    NEGATIVE_SLOPE: 0.05
    FEATURE_DIM: 128 # Feature dimension of PointNet
  TRAIN:
    PATIENCE: 5
    LEARNING_RATE: 0.001
    LR_MODE: "min"
    LR_FACTOR: 0.1
    LR_PATIENCE: 3
    EPOCHS: 200
    OPTIMIZER: "adam" # Options: "adam", "sgd"

# LOGGING
LOGGING:
  # LOG_FILE: "./logs/local_logs.log"
  LOG_LEVEL: "DEBUG"
  # LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
